#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/mongo )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker buildx build --file custom/argo-workflow-executor/Dockerfile --progress plane --push --no-cache --platform linux/arm64,linux/amd64 --tag litmuschaos/mongo:4.2.8 .
else
  echo "No docker credentials provided. Skip uploading litmuschaos/mongo:4.2.8 to docker hub";
fi;
