apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: prometheus-k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31090
