#!/bin/bash
set -e

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then

  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker buildx build . -f Dockerfile --progress plain --push --no-cache --platform linux/amd64,linux/arm64 --tag litmuschaos/mongo-utils:0.1.0 --tag litmuschaos/mongo-utils:latest
else
  echo "No docker credentials provided. Skip uploading litmuschaos/mongo-utils:4.0.5 to docker hub";
fi;
