apiVersion: v1
kind: Secret
metadata:
  labels:
    application: spilo
    cluster-name: postgres-application
    team: postgres
  name: postgres-application.credentials
  namespace: litmus
  annotations:  
    kubernetes.io/service-account.name: litmus-admin
data:
  username: emFsYW5kbw== # zalando
  password: MlNzWnNUN2ZINXZKQVB4eXp1NDV0bHF5VVpibDc0SWpWYXNUalpnZWxsZG9ZZlRQR1BZbmxQc1ZvUEdyNmpzdQ==
  host: cG9zdGdyZXMtYXBwbGljYXRpb24ucG9zdGdyZXMuc3ZjCg== # postgres-application
  dbname: cG9zdGdyZXMK # postgres
  port: NTQzMgo= # 5432
type: kubernetes.io/service-account-token 