apiVersion: batch/v1
kind: Job
metadata:
  name: app-cpu-stress
spec:
  template:
    metadata:
      labels:
        app: app-cpu-stress
    spec:
      nodeSelector:
        ## mandatory: provide name of host where target container resides
        kubernetes.io/hostname: ""
      restartPolicy: Never
      containers:
      - image: litmuschaos/app-cpu-stress:ci
        imagePullPolicy: Always
        name: app-cpu-stress
        command: 
        - /bin/sh
        args:
        - ./cpu-hog.sh 
        env:
            ## mandatory: provide id of docker container
          - name: CONTAINER_ID
            value: ""
            ## optional: provide duration of cpu chaos 
            ## default: 60 (in sec)
          - name: DURATION
            value: ""
            ## optional: provide number of cpu cores to be consumed in container
            ## default: 1
          - name: CORES
            value: ""
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
