#!/bin/bash
set -e

IMAGEID=$( docker images -q openebs/service-liveness )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} openebs/service-liveness:latest
  docker push openebs/service-liveness:latest; 
else
  echo "No docker credentials provided. Skip uploading openebs/service-liveness:latest to docker hub"; 
fi;
