#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/container-killer )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/container-killer:latest
  docker push litmuschaos/container-killer:latest; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/container-killer:latest to docker hub"; 
fi;
