#!/bin/bash
set -e

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker buildx build -f Dockerfile --progress plain --push --no-cache --platform linux/amd64,linux/arm64 --tag litmuschaos/argoexec:v3.3.1 .
else
  echo "No docker credentials provided. Skip uploading litmuschaos/argoexec:v3.3.1 to docker hub";
fi;
