#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/litmus-git-app-checker)

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/litmus-git-app-checker:latest
   docker buildx build . -f Dockerfile --progress plane --push --no-cache --platform linux/amd64,linux/arm64 --tagss litmuschaos/litmus-git-app-checker:latest;
else
  echo "No docker credentials provided. Skip uploading litmuschaos/litmus-git-app-checker:latest to docker hub";
fi;
