apiVersion: batch/v1
kind: Job
metadata:
  name: fortio
  labels:
    app: fortio
spec:
  template:
    spec:
      volumes:
      - name: shared
        emptyDir: {}
      containers:
      - name: fortio
        image: fortio/fortio
        # provide the url of the target service
        command: ["fortio", "load", "-t", "60s", "-qps", "2000", http://35.188.165.74]
        volumeMounts:
        - name: shared
          mountPath: /shared              
      restartPolicy: Never