{
 "title": "Node and Pod Chaos Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Litmus Chaos Chaos durations interleaved with Node Exporter & Kube-State Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Chaos - Node - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Node - Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\"}) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  }
 ]
}
{
 "title": "PXC/Galera Node Summary",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node",
    "query": {
     "query": "label_values(mysql_global_status_wsrep_local_state, node_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysql_galera_variables_info, wsrep_cluster_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "query_result(mysql_galera_variables_info{wsrep_cluster_name=~\"$cluster\"} * on(service_name) mysql_global_variables_wsrep_rsu_commit_timeout)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready to Accept Queries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_ready{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "Local State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_local_state{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "Desync Mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_wsrep_desync{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_cluster_status{service_name=~\"$service_name\"}"
    }
   ]
  },
  {
   "title": "gcache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) (mysql_galera_gcache_size_bytes{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "FC (normal traffic)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by (service_name) (mysql_global_status_wsrep_flow_control_status{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Galera Replication Latency",
   "type": "graph",
   "description": "Shows figures for the replication latency on group communication. It measures latency from the time point when a message is sent out to the time point when a message is received. As replication is a group operation, this essentially gives you the slowest ACK and longest RTT in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name,aggregator) (max_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Maximum\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Maximum\"}[5m]))",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "avg by (service_name,aggregator) (avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Standard Deviation\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Standard Deviation\"}[5m]))",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "avg by (service_name,aggregator) (avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Average\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Average\"}[5m]))",
     "legendFormat": "{{ aggregator }}"
    },
    {
     "expr": "avg by (service_name,aggregator) (min_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Minimum\"}[$interval]) or\nmin_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service_name\", aggregator=\"Minimum\"}[5m]))",
     "legendFormat": "{{ aggregator }}"
    }
   ]
  },
  {
   "title": "Galera Replication Queues",
   "type": "graph",
   "description": "Shows the length of receive and send queues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Receive Queue"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Send Queue"
    }
   ]
  },
  {
   "title": "Galera Cluster Size",
   "type": "graph",
   "description": "Shows the number of members currently connected to the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_cluster_size{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cluster_size{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Galera Flow Control",
   "type": "graph",
   "description": "Shows the number of FC_PAUSE events sent/received. They are sent by a node when its replication queue gets too full. If a node is sending out FC messages it indicates a problem.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "FC Messages Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "FC Messages Sent"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) ((rate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service_name\"}[5m])))/1000000000",
     "legendFormat": "Paused due to Flow Control"
    }
   ]
  },
  {
   "title": "Galera Parallelization Efficiency",
   "type": "graph",
   "description": "Shows the average distances between highest and lowest seqno that are concurrently applied, committed and can be possibly applied in parallel (potential degree of parallelization).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Apply Window"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Commit Window"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (max_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Cert Deps Distance"
    }
   ]
  },
  {
   "title": "Galera Writing Conflicts",
   "type": "graph",
   "description": "Shows the number of local transactions being committed on this node that failed certification (some other node had a commit that conflicted with ours) – client received deadlock error on commit and also the number of local transactions in flight on this node that were aborted because they locked something an applier thread needed – deadlock error anywhere in an open transaction. Spikes in the graph may indicate writing to the same table potentially the same rows from 2 nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Local Cert Failures"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Local Bf Aborts"
    }
   ]
  },
  {
   "title": "Available Downtime before SST Required",
   "type": "graph",
   "description": "Shows for how long the node can be taken out of the cluster before SST is required. SST is a full state transfer method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (mysql_galera_gcache_size_bytes{service_name=~\"$service_name\"}) /\nignoring(job) (avg by (service_name) (rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[1h])+rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[1h])))",
     "legendFormat": "Time (1h avg)"
    },
    {
     "expr": "avg by (service_name) (mysql_galera_gcache_size_bytes{service_name=~\"$service_name\"}) /\nignoring(job) (avg by (service_name) ((rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[5m])) + \n(rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[5m]))))",
     "legendFormat": "Time (Instant)"
    }
   ]
  },
  {
   "title": "Galera Writeset Count",
   "type": "graph",
   "description": "Shows the count of transactions received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_received{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Transactions Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_replicated{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Transactions Replicated"
    }
   ]
  },
  {
   "title": "Galera Writeset Size",
   "type": "graph",
   "description": "Shows the average transaction size received/replicated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[$interval]) / rate(mysql_global_status_wsrep_received{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[5m]) / irate(mysql_global_status_wsrep_received{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Incoming Transaction Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[$interval]) / rate(mysql_global_status_wsrep_replicated{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[5m]) / irate(mysql_global_status_wsrep_replicated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Replicating Transaction Size"
    }
   ]
  },
  {
   "title": "Galera Writeset Traffic",
   "type": "graph",
   "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Galera Network Usage Hourly",
   "type": "graph",
   "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (increase(mysql_global_status_wsrep_received_bytes{service_name=~\"$service_name\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (increase(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service_name\"}[1h]))",
     "legendFormat": "Replicated"
    }
   ]
  }
 ]
}
{
 "title": "Kafka: Cluster Summary",
 "description": "KUDO Kafka Cluster Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   },
   {
    "name": "broker",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_brokers{namespace=\"$namespace\",service=\"kafka-exporter\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Sync Connects / sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_SessionExpireListener_ZooKeeperSyncConnects_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Leader Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaManager_LeaderCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Topic Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (topic) (kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\"}))"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaManager_PartitionCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "ActiveController for ($service)",
   "type": "graph",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_ActiveControllerCount{namespace=\"$namespace\",service=\"$service\"})by(pod, service)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage: $broker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}) / node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
     "legendFormat": "USED: {{$broker}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Load %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_SocketServer_NetworkProcessorAvgIdlePercent{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions for $service",
   "type": "singlestat",
   "description": "In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.\n\nIf this metric has a value greater than 1 it means that data is not being replicated to enough number of brokers thereby increasing the probability of data loss.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_UnderReplicatedPartitions{service=\"$service\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_ActiveControllerCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Messages In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Messages In Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Disk Used / Broker",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"}) / node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{pod}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Used / Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{pod}} {{area}}"
    }
   ]
  },
  {
   "title": "Messages / Topic",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_MessagesIn_total{service=\"$service\", namespace=\"$namespace\", topic=\"\"}[1m]))",
     "legendFormat": "messages/second"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesIn_total{service=\"$service\", namespace=\"$namespace\", topic=\"\"}[1m]))",
     "legendFormat": "bytes in /second"
    }
   ]
  },
  {
   "title": "All Bytes In",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All Bytes Out",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesOut_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Broker Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Partition Count (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_controller_KafkaController_GlobalPartitionCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ISR Shrink Rate (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_ReplicaManager_IsrShrinks_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Offline Partitions for ($service) broker ($broker)",
     "type": "graph",
     "description": "This value should be 0",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_controller_KafkaController_OfflinePartitionsCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Producer Purgatory Requests Waiting for ($service) broker ($broker)",
     "type": "graph",
     "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_DelayedOperationPurgatory_NumDelayedOperations{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ISR Expansion Rate (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_ReplicaManager_IsrExpands_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delayed Fetch Operation Purgatory Size for ($service) broker ($broker)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_DelayedOperationPurgatory_PurgatorySize{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Partition Count Across Brokers for ($service) broker ($broker)",
     "type": "graph",
     "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_ReplicaManager_PartitionCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Derivative messages/sec for ($broker) / topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$broker\", topic=~\".+\"}[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "All Bytes In per (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\", topic=~\".+\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "All Bytes Out per (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_BrokerTopicMetrics_BytesOut_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\", topic=~\".+\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "bytes in / sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"}[1m]))",
       "legendFormat": "{{ $broker }} - bytes in /second "
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(topic) (kafka_cluster_Partition_UnderReplicated{namespace=\"$namespace\",namespace=\"$namespace\",service=\"$service\"})"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
       "legendFormat": "TOTAL: {{pod}}"
      },
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
       "legendFormat": "USED: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}