#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/kafka-deployer )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/kafka-deployer:latest
  docker push litmuschaos/kafka-deployer:latest; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/kafka-deployer:latest to docker hub"; 
fi;
