#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/cassandra-client )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/cassandra-client:latest
  docker push litmuschaos/cassandra-client:latest; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/cassandra-client:latest to docker hub"; 
fi;
