#!/bin/bash
set -e

IMAGEID=$( docker images -q openebs/linux-utils )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with alpine version tag
  docker tag ${IMAGEID} openebs/linux-utils:3.10
  docker push openebs/linux-utils:3.10;
else
  echo "No docker credentials provided. Skip uploading openebs/linux-utils:3.10 to docker hub";
fi;

if [ ! -z "${QNAME}" ] && [ ! -z "${QPASS}" ];
then

  docker login -u "${QNAME}" -p "${QPASS}" quay.io;

	#Push to docker hub repository with alpine version tag
  docker tag openebs/linux-utils:3.10 quay.io/openebs/linux-utils:3.10
  docker push quay.io/openebs/linux-utils:3.10;
else
  echo "No docker credentials provided. Skip uploading quay.io/openebs/linux-utils:3.10 to docker hub";
fi;
