#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/k8s )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/k8s:latest
  docker push litmuschaos/k8s:latest;
else
  echo "No docker credentials provided. Skip uploading litmuschaos/k8s:latest to docker hub";
fi;