#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/argocli )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/argocli:v2.9.3
  docker push litmuschaos/argocli:v2.9.3;
else
  echo "No docker credentials provided. Skip uploading litmuschaos/argocli:v2.9.3 to docker hub";
fi;