---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chaos-exporter
  name: chaos-exporter
  namespace: litmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-exporter
  template:
    metadata:
      labels:
        app: chaos-exporter
    spec:
      containers:
      - image: litmuschaos/chaos-exporter:ci
        imagePullPolicy: Always
        name: chaos-exporter
        env:
        - name: WATCH_NAMESPACE
          value: ''
      serviceAccountName: litmus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaos-exporter
  name: chaos-exporter
  namespace: litmus
spec:
  ports:
  - port: 8080
    name: tcp
    protocol: TCP
    targetPort: 8080
  selector:
    app: chaos-exporter
  type: NodePort
  
