#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/pod-delete-chaos:latest)

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker push litmuschaos/pod-delete-chaos; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/pod-delete-chaos:latest to docker hub"; 
fi;

