#!/bin/bash
set -e

IMAGEID=$(docker images -q litmuschaos/sysbench)

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} litmuschaos/sysbench:latest
  docker push litmuschaos/sysbench:latest; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/sysbench:latest to docker hub"; 
fi;
