#!/bin/bash
set -e

IMAGEID=$( docker images -q litmuschaos/stress-ng:latest)

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker push litmuschaos/stress-ng; 
else
  echo "No docker credentials provided. Skip uploading litmuschaos/stress-ng:latest to docker hub"; 
fi;

